import Protect from '@/components/layout/Protect';
import { UserContextProvider } from '@/context/UserContext';
import '@/sass/main.scss'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Protect>
            {children}
          </Protect>
        </UserContextProvider>
      </body>
    </html>
  );
}
