import Protect from '@/components/layout/Protect';
import { EventContextProvider } from '@/context/EventContext';
import { UserContextProvider } from '@/context/UserContext';
import '@/sass/main.scss'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <EventContextProvider>
            <Protect>
              {children}
            </Protect>
          </EventContextProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
