import { useContext } from 'react'
import ImageContext from '@/context/ImageContext'
import Head from 'next/head'
import Container from '@/components/layout/Container'
import HomeHeader from '@/components/home/HomeHeader'
import Grid from '@/components/common/grid/Grid'

export default function Home() {

  const { images, bookmarks, activeBookmark, setActiveBookmark } = useContext(ImageContext);
  
  const setActive = (index) => {
    setActiveBookmark(index);
  }

  return (
    <>
      <Head>
        <title>Minite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <HomeHeader active={activeBookmark} setActive={setActive} bookmarks={bookmarks}/>

        { images && <Grid images={images} />}

      </Container>
    </>
  )
}
