import Head from 'next/head'
import Container from '@/components/layout/Container'
import HomeHeader from '@/components/home/HomeHeader'

export default function Home() {
  
  const setActive = (index) => {
    
  }

  return (
    <>
      <Head>
        <title>Minite</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <HomeHeader active={1} setActive={setActive} />
      </Container>
    </>
  )
}
